### ISSUE TITLE
Nuxt SSR support

### ISSUE THREAD

**Issue by productfrontenddeveloper** [smaharj1/vue-drag-and-drop-kanban#30]
Can you prepare the installation documentation for nuxt, and does ssr support it?

**Comment by smaharj1** [comment]
Hello I have updated the documentation about Nuxt. It currently doesn't support the SSR, but you could tell Nuxt to render in client side. I have updated the documentation on how to do that. Closing this issue about documentation for Nuxt.

**Comment by productfrontenddeveloper** [comment]
I will be using it soon in my project. Thank you.
