### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by KIlian42** [smaharj1/vue-drag-and-drop-kanban#59]
I do not understand the documentation. Where do I include 'MyComponent.vue' to get the exact same output as in the image?

**Comment by smaharj1** [comment]
Hello. I need to update the documentation, but the `MyComponent.vue` is basically `CustomCard.vue` in the repository. https://github.com/smaharj1/vue-drag-and-drop-kanban/blob/master/src/App.vue
